# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minisql < Formula
  desc "Embedded single-file SQL database in pure Go — faster than SQLite on latency benchmarks."
  homepage "https://github.com/RichardKnop/minisql"
  version "0.100.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RichardKnop/minisql/releases/download/v0.100.0/minisql_0.100.0_darwin_amd64.tar.gz"
      sha256 "150c7e4c29c64fc3279fe0e82d6d642053d456b0868cb15bd279eea271c9facb"

      define_method(:install) do
        bin.install "minisql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RichardKnop/minisql/releases/download/v0.100.0/minisql_0.100.0_darwin_arm64.tar.gz"
      sha256 "16f6187293dd02a059cf1655b174d689601131740d8bcc6d895d53a216109d41"

      define_method(:install) do
        bin.install "minisql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RichardKnop/minisql/releases/download/v0.100.0/minisql_0.100.0_linux_amd64.tar.gz"
      sha256 "8371106f2cb2f2c062a3f80db1fc8984687a4c6dbf76e7919fe7c7f3616d27b5"
      define_method(:install) do
        bin.install "minisql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RichardKnop/minisql/releases/download/v0.100.0/minisql_0.100.0_linux_arm64.tar.gz"
      sha256 "57cfe9ca997b272709ec3d44ef52e812d16608ea75028101c52e7ca356943b4c"
      define_method(:install) do
        bin.install "minisql"
      end
    end
  end

  test do
    system "#{bin}/minisql", "-version"
  end
end
