# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minisql < Formula
  desc "Embedded single-file SQL database in pure Go — faster than SQLite on latency benchmarks."
  homepage "https://github.com/RichardKnop/minisql"
  version "1.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RichardKnop/minisql/releases/download/v1.10.0/minisql_1.10.0_darwin_amd64.tar.gz"
      sha256 "43951848c162d8d3b446ab73af0ccb2e01da7beeba38edec1f9a62fa1c202376"

      define_method(:install) do
        bin.install "minisql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RichardKnop/minisql/releases/download/v1.10.0/minisql_1.10.0_darwin_arm64.tar.gz"
      sha256 "bcbd1994762f73a68c68391318f9ca77bc9f3a22d259b9bbd9527e6ae5ef54cb"

      define_method(:install) do
        bin.install "minisql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RichardKnop/minisql/releases/download/v1.10.0/minisql_1.10.0_linux_amd64.tar.gz"
      sha256 "82e96e2d4e7202192020d18db92c5b1a84ef10e6180c0a47eb91fec0797d9fe6"
      define_method(:install) do
        bin.install "minisql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RichardKnop/minisql/releases/download/v1.10.0/minisql_1.10.0_linux_arm64.tar.gz"
      sha256 "6b13b9faca855d7de71a8f6dc4bcff0913abdeb053c286c99fafa4bf580b06cd"
      define_method(:install) do
        bin.install "minisql"
      end
    end
  end

  test do
    system "#{bin}/minisql", "-version"
  end
end
